### ISSUE TITLE
black config - 120 chars?

### ISSUE THREAD

**Issue by albertz** [rwth-i6/i6_experiments#118]
I would propose the following `pyproject.toml` config:
```
[tool.black]
line-length = 120
target-version = ["py37"]
```
Currently black uses the default 88 chars. So this would change it to 120 chars. I personally would prefer that. Any objections?
I'm not so sure about the Python `target-version` but I guess Python >=3.7 is ok?

**Comment by JackTemaki** [comment]
I also prefer 120. Target version is ok.

**Comment by albertz** [comment]
Corresponding issue in i6_core: https://github.com/rwth-i6/i6_core/issues/362

**Comment by albertz** [comment]
So, it is decided then? Or what exactly do we wait for now?

**Comment by JackTemaki** [comment]
we wait for any response in https://github.com/rwth-i6/i6_core/issues/362

**Comment by albertz** [comment]
Why? Because you want it consistent to that? We can also decide independently here, or not?

**Comment by christophmluscher** [comment]
I would keep the decision consistent but the timing independent between core and experiments.

Since I have a number of PR on common/rasr, if possible, I would like to to the black with 120 on those files.

**Comment by albertz** [comment]
I mean, we can also argue that it should be consistent to RETURNN-common, or RETURNN.

But it anyway seems like most people vote for 120.

**Comment by christophmluscher** [comment]
IMHO core and experiments are both Sisyphus recipes. Returnn and returnn common are not.
I'd rather argue Sisyphus should have the same black rules than returnn

**Comment by albertz** [comment]
Ok, @curufinwe agreed to 120 chars in i6_core (https://github.com/rwth-i6/i6_core/issues/362). I guess it is decided then that we use 120 chars both here in i6_exp and in i6_core.

I will just apply it directly here in i6_exp. Someone else can do it for i6_core.
