### ISSUE TITLE
[Returnn torch] Collection joins serializer objects without newlines

### ISSUE THREAD

**Issue by mnghiap** [rwth-i6/i6_experiments#209]
https://github.com/rwth-i6/i6_experiments/blob/76ccb59ec91105c1e50faade08b0c2b40307ecf9/common/setups/returnn_pytorch/serialization.py#L140

This causes problems when the `SerializerObject`s in the `Collection` don't have a new line at the end. For example, in my code, I have 3 consecutive `Call` objects in the `Collection`, which was serialized like this:

`teacher_ctc_config = ConformerCTCConfig(...)student_lm_config = LSTMLMConfig(...)cfg = MultiModelWrapperConfig(...)
`

**Comment by JackTemaki** [comment]
After checking the rest of the code, it seems other Serializer objects such as "Import" or "CodeFromFunction" add their own newlines. So there should be no problem in doing this for the call. 

For the Serializer itself it is not clear if there ever is a case where you do not want a newline...

@mnghiap Can you do a PR simply for adding the newline at the end of the call? This is definitely a safe thing to do.

**Comment by JackTemaki** [comment]
resolved with #210
