### ISSUE TITLE
function: get_tf_flow

### ISSUE THREAD

**Issue by christophmluscher** [rwth-i6/i6_experiments#41]
Location of `nn_system->get_tf_flow` could be improved: `i6_experiments/commom/setups/flow/tf.py` or `i6_core/returnn/flow.py` or so

**Comment by JackTemaki** [comment]
The pipeline can now be updated with:

https://github.com/rwth-i6/i6_core/pull/307

**Comment by JackTemaki** [comment]
Solved via #101
